name: PMR Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Install dependencies
      run: |
        brew install swiftlint
        
    - name: Run Unit Tests
      run: make unit
      
    - name: Run UI Tests
      run: make ui
      
    - name: Run Snapshot Tests
      run: make snapshot
      
    - name: Run Link Checker
      run: make links
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: |
          ~/Library/Logs/DiagnosticReports
          /tmp/XCTestOutput*.txt